# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`RDF-NS-Curated`
	:test-requirement       [ :on "Test::More 0.96"^^:CpanId ];
        :runtime-requirement    [ :on "perl 5.006000"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
	:develop-recommendation [ :on "RDF::Trine"^^:CpanId ];
	:develop-recommendation [ :on "Test::Exception"^^:CpanId ];
	:develop-recommendation [ :on "List::Util 1.43"^^:CpanId ];
	.

