name: Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  create:

env:
  IRC_CHANNEL: '#perlrdf'
  IRC_SERVER: 'irc.perl.org'
  IRC_PORT: '6667'
  IRC_NICKNAME: 'perlrdf-commits'
  IRC_GITHUB_REPO: 'perlrdf/p5-rdf-ns-curated'

jobs:
  notify:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ always() }}
    steps:
      - name: irc push
        uses: Gottox/irc-message-action@v1.3
        if: ${{ github.event_name == 'push' && github.repository == 'perlrdf/p5-rdf-ns-curated' }}
        with:
          channel: ${{ env.IRC_CHANNEL }}
          server: ${{ env.IRC_SERVER }}
          port: ${{ env.IRC_PORT }}
          nickname: ${{ env.IRC_NICKNAME }}
          tls: false
          notice: true
          message: |
            ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }}
            ${{ join(github.event.commits.*.message, ', ') }}
      - name: irc pull request
        uses: Gottox/irc-message-action@v1.3
        if: ${{ github.event_name == 'pull_request' && github.repository == 'perlrdf/p5-rdf-ns-curated' }}
        with:
          channel: ${{ env.IRC_CHANNEL }}
          server: ${{ env.IRC_SERVER }}
          port: ${{ env.IRC_PORT }}
          nickname: ${{ env.IRC_NICKNAME }}
          tls: false
          notice: true
          message: |
            ${{ github.actor }} ${{ github.event.action }} PR «${{ github.event.pull_request.title }}» ${{ github.event.pull_request.html_url }}
      - name: irc tag created
        uses: Gottox/irc-message-action@v1.3
        if: ${{ github.event_name == 'create' && github.event.ref_type == 'tag' && github.repository == 'perlrdf/p5-rdf-ns-curated' }}
        with:
          channel: ${{ env.IRC_CHANNEL }}
          server: ${{ env.IRC_SERVER }}
          port: ${{ env.IRC_PORT }}
          nickname: ${{ env.IRC_NICKNAME }}
          tls: false
          notice: true
          message: |
            ${{ github.actor }} tagged ${{ github.repository }} ${{ github.event.ref }}
  dist:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    env:
      DIST_INKT_PROFILE: "Dist::Inkt::Profile::KJETILK"
    name: Make distribution
    runs-on: ubuntu-latest
    outputs:
      min-perl-version: ${{ steps.min-perl.outputs.min-perl-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache ~/perl5
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-dist-locallib
          path: ~/perl5
      - name: Perl version
        run: |
          perl -v
      - name: Install cpanm
        run: |
          curl -L https://cpanmin.us | perl - --sudo App::cpanminus
      - name: Install local::lib
        run: |
          cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
      - name: Install Dist::Inkt
        shell: bash
        run: |
          eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          cpanm -n ExtUtils::MakeMaker~6.31 Dist::Inkt "$DIST_INKT_PROFILE"
      - name: Make distribution
        shell: bash
        run: |
          eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          distinkt-dist --TRAVIS --targetdir=build-dir
      - name: Find min Perl version
        shell: bash
        id: min-perl
        run: |
          eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          perl -Mversion -MList::Util=max -e '
                my $v = version->parse( $ARGV[0] );
                # ExtUtils::MakeMaker  : "5.006001"
                # CPAN::Meta           : "5.008001"
                my $min_from_toolchain = version->parse("5.008001");
                $v = max( $v, $min_from_toolchain );
                my $dotted = $v->normal;
                print "::set-output name=min-perl-version::$dotted\n"' \
            $( jq -r '.prereqs.runtime.requires.perl' < build-dir/META.json  )
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./build-dir
  test:
    needs: [ 'dist', 'notify' ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        perl: ['5']
        include:
          - { os: 'ubuntu-latest', perl: "5.14" }
          - { os: 'ubuntu-latest', perl: "5.16" }
          - { os: 'ubuntu-latest', perl: "5.20" }
          - { os: 'ubuntu-latest', perl: "5.30" }
          - { os: 'ubuntu-latest', perl: "5.32" }
          - { os: 'ubuntu-latest', perl: "${{ needs.dist.outputs.min-perl-version  }}" }
          - { os: 'ubuntu-latest', perl: "latest" }
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}

    steps:
      - name: Get dist artifact
        uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        if: matrix.os != 'windows-latest'
        with:
          perl-version: ${{ matrix.perl }}
      - name: Set up perl (Strawberry)
        uses: shogo82148/actions-setup-perl@v1
        if: matrix.os == 'windows-latest'
        with:
          distribution: 'strawberry'

      - run: perl -V

      - name: Install Perl deps
        run: |
          cpanm --notest ExtUtils::MakeMaker~6.31 CPAN::Meta
          cpanm --notest --installdeps .

      - name: Run tests
        run: |
          cpanm --verbose --test-only .
  build-status:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ ( github.event_name == 'push' || github.event_name == 'pull_request' ) && ( success() || failure() ) && github.repository == 'perlrdf/p5-rdf-ns-curated' }}
    needs: test
    steps:
      - name: Prepare message
        run: |
          echo "GITHUB_WORKFLOW_URL=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV
      - name: IRC build success
        uses: Gottox/irc-message-action@v1.3
        if: ${{ ! contains(needs.*.result, 'failure') && ! contains(needs.*.result, 'cancelled') }}
        with:
          channel: ${{ env.IRC_CHANNEL }}
          server: ${{ env.IRC_SERVER }}
          port: ${{ env.IRC_PORT }}
          nickname: ${{ env.IRC_NICKNAME }}
          tls: false
          notice: true
          message: |
            Build status: All builds succeeded [${{ github.event_name }}]: ${{ env.GITHUB_WORKFLOW_URL }}
            @ ${{ github.sha }} | ${{ github.event.commits[0].author.name }} | «${{ github.event.commits[0].message }}»
      - name: IRC build failure
        uses: Gottox/irc-message-action@v1.3
        if: ${{ contains(needs.*.result, 'failure') }}
        with:
          channel: ${{ env.IRC_CHANNEL }}
          server: ${{ env.IRC_SERVER }}
          port: ${{ env.IRC_PORT }}
          nickname: ${{ env.IRC_NICKNAME }}
          tls: false
          notice: true
          message: |
            Build status: Some builds failed [${{ github.event_name }}]: ${{ env.GITHUB_WORKFLOW_URL }}
            @ ${{ github.sha }} | ${{ github.event.commits[0].author.name }} | «${{ github.event.commits[0].message }}»
